# Generated by Django 5.0.6 on 2024-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_taller_inscripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='taller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='fecha_inscripcion',
        ),
    ]
