# Generated by Django 5.1.4 on 2024-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_inscripcion_unique_together_alter_taller_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(default='Valor por defecto', max_length=50),
        ),
    ]
